production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: timesheet_app_production
  username: timesheet_app
  password: <%= ENV["TIMESHEET_APP_DATABASE_PASSWORD"] %>